{'name': 'Hydromotor - Комплекти части за машини',
 'version': '19.0.1.1.0',
 'summary': 'Машина ↔ комплект ↔ оферта; избор на възел или отделни части',
 'author': 'Hydromotor',
 'license': 'LGPL-3',
 'depends': ['hydromotor_service', 'sale_management'],
 'data': ['models/definitions.xml',
          'models/quotation_fields.xml',
          'security/access.xml',
          'security/quotation_access.xml',
          'actions/quotation_actions.xml',
          'views/views.xml'],
 'application': False,
 'installable': True,
 'auto_install': False,
 'pre_init_hook': 'pre_init_hook'}
