{'name': 'Hydromotor Bilingual PDF Naming',
 'version': '19.0.2.0.1',
 'summary': 'BG/EN PDF names and separate article numbers in products, documents and reports',
 'category': 'Hidden/Tools',
 'author': 'Hydromotor OOD',
 'license': 'LGPL-3',
 'depends': ['sale', 'account', 'stock', 'purchase'],
 'data': ['views/res_users_views.xml',
          'views/report_user_names.xml',
          'data/report_actions.xml',
          'views/article_reference_views.xml',
          'report/article_reference_reports.xml'],
 'installable': True,
 'application': False,
 'auto_install': False,
 'assets': {'web.assets_backend': ['hydromotor_report_naming/static/src/js/article_utils.js',
                                   'hydromotor_report_naming/static/src/js/article_reference.js']}}
