{'name': 'Hydromotor — Машини, CRM и Продажби',
 'version': '19.0.1.0.6',
 'summary': 'Recovered from latest Hydromotor backup; Odoo 19.0 development candidate',
 'author': 'Hydromotor',
 'license': 'LGPL-3',
 'depends': ['base', 'base_automation', 'hydromotor_service', 'sale_management', 'sale_crm'],
 'data': ['models/definitions.xml',
          'security/access.xml',
          'data/defaults.xml',
          'views/actions_and_views.xml',
          'data/automations.xml'],
 'application': True,
 'installable': True,
 'auto_install': False,
 'pre_init_hook': 'pre_init_hook'}
